/* 发芽搭子（原 Slim Partner）V3 —— 统一搭子 SKU 数据层
   分类：身心 / 搞钱 / 关系 / 自我（用户认知的 MECE），每类下有子模块
   交叉标签：同一个搭子可同时属于多个情绪/场景，搜索与推荐按痛点情绪走
   新增搭子 = 在这里加一条数据，不再新写页面 */
window.V3 = {
  brand: {
    name: '发芽搭子',
    en: 'FAYA',
    slogan: '人生很复杂，你不用一个人扛。',
    sub: '找一个搭子，陪你发芽。',
    footer: '慢慢来，比较快。陪你发芽的地方。'
  },
  /* —— 一级品类（左侧导航 = 用户心智的 MECE） —— */
  cats: [
    { key: 'all',   label: '全部', emoji: '✨', tip: '现在最想改善什么，就从那里开始。' },
    { key: 'bm',    label: '身心', emoji: '🌿', tip: '先照顾好身体和情绪，很多事会慢慢变轻。' },
    { key: 'money', label: '搞钱', emoji: '💰', tip: '不是让你更卷，是陪你把钱和能力攒起来。' },
    { key: 'rel',   label: '关系', emoji: '❤️', tip: '关系顺了，日子就顺了大半。' },
    { key: 'self',  label: '自我', emoji: '🌱', tip: '慢慢长出让你自己踏实的那部分。' }
  ],
  /* —— 二级子模块（右侧分区内的小标题，不强迫用户二选一） —— */
  subs: {
    bm:    [{ key: 'phys',  label: '身体管理' }, { key: 'mind', label: '心理疗愈' }, { key: 'daily', label: '日常状态' }],
    money: [{ key: 'career', label: '职场晋升' }, { key: 'biz',  label: '创业搞钱' }, { key: 'wealth', label: '财务底盘' }],
    rel:   [{ key: 'heal',  label: '情感疗愈' }, { key: 'family', label: '家人亲子' }, { key: 'social', label: '沟通连接' }],
    self:  [{ key: 'think', label: '认知成长' }, { key: 'act',   label: '行动习惯' }, { key: 'meaning', label: '意义方向' }]
  },
  /* —— 首页「你现在更接近哪种状态」：按痛点情绪，而不是按品类 —— */
  moods: [
    { key: 'pain',  emoji: '😞', label: '最近很痛苦', ids: ['breakup', 'state', 'mindset'] },
    { key: 'sleep', emoji: '😴', label: '睡不好',     ids: ['sleep', 'health', 'morning'] },
    { key: 'burn',  emoji: '🌀', label: '很内耗',     ids: ['mindset', 'subject', 'state'] },
    { key: 'work',  emoji: '💼', label: '工作卡住了', ids: ['p78', 'owner', 'leader'] },
    { key: 'rel',   emoji: '💔', label: '关系很累',   ids: ['guanxi', 'family', 'breakup'] },
    { key: 'dir',   emoji: '🧭', label: '找不到方向', ids: ['mission', 'restart40', 'longterm'] },
    { key: 'money', emoji: '💰', label: '存不下钱',   ids: ['finance', 'startup', 'aiopc'] },
    { key: 'move',  emoji: '🏃', label: '想动起来',   ids: ['move', 'slim', 'muscle'] }
  ],
  personalities: [
    { key: 'gentle', emoji: '🌸', name: '温柔一点', quote: '今天做一点就很好。' },
    { key: 'push',   emoji: '🔥', name: '推我一把', quote: '别等状态，现在做第一步。' },
    { key: 'logic',  emoji: '📊', name: '理性一点', quote: '先解决最大的阻力。' }
  ],
  partners: [
    /* ═══════════ 身心 · 身体管理 ═══════════ */
    { id: 'sleep', cat: 'bm', sub: 'phys', icon: '😴', name: '睡眠搭子', href: '搭子-睡眠.html',
      promise: '陪你重新建立稳定的睡眠节律。', alias: '睡觉 失眠 熬夜',
      problems: ['明明很累，却迟迟睡不着', '到晚上就舍不得放下手机', '睡够了，还是感觉累'],
      short: ['入睡困难', '熬夜', '作息乱'],
      tags: ['#睡眠', '#作息', '#熬夜', '#身体健康'],
      duration: '7天体验', dailyTime: '每天约5分钟', badge: '热门',
      tasks: ['14:00 以后不喝咖啡', '睡前30分钟把手机放远一点', '上床后做3次缓慢呼吸'],
      suit: ['想改善睡眠但很难坚持', '不喜欢严格打卡', '更希望慢慢建立习惯'],
      unsuit: ['希望获得医学诊断', '有持续严重睡眠问题'],
      safety: '如存在持续或严重睡眠问题，应优先寻求专业医疗帮助。' },
    { id: 'slim', cat: 'bm', sub: 'phys', icon: '🥗', name: '减肥搭子', href: 'index.html',
      promise: '不逼你节食，陪你建立能坚持的生活习惯。', alias: '减脂 瘦身 体重',
      problems: ['试过节食，总是反弹', '知道该少吃多动，就是做不到', '体重反反复复，越来越没信心'],
      short: ['易反弹', '难坚持', '反复胖'],
      tags: ['#减脂', '#饮食习惯', '#意志力', '#身体健康'],
      duration: '21天陪伴', dailyTime: '每天约5分钟', badge: '热门',
      tasks: ['今天吃了什么？记一笔就好', '饭后慢慢走10分钟', '23:30 前准备上床'],
      suit: ['想减脂但不想饿肚子', '不喜欢严格打卡', '想慢慢建立饮食习惯'],
      unsuit: ['需要医学减重方案', '有进食障碍史'],
      safety: '本搭子用于习惯建立与日常支持，不提供医学诊断或治疗；如有健康问题请优先寻求专业医疗帮助。' },
    { id: 'move', cat: 'bm', sub: 'phys', icon: '🏃', name: '活力唤醒搭子', href: '', soon: true,
      promise: '不比谁狠，陪你把身体一点点唤醒起来。', alias: '运动 健身 跑步 不想动',
      problems: ['办了健身卡，去了两次就放着', '知道要动，就是提不起劲', '一练就酸痛，然后彻底放弃'],
      short: ['启动难', '三天热度', '怕酸痛'],
      tags: ['#运动', '#身体健康', '#意志力', '#习惯矫正'],
      duration: '21天计划', dailyTime: '每天约10分钟', badge: '新上线',
      tasks: ['今天出门快走15分钟', '做一个最简单的热身组合', '记一句：动完之后感觉怎么样'],
      suit: ['久坐、体能下滑的打工人', '想动但总启动不了', '不想被高强度训练吓退'],
      unsuit: ['有运动损伤未恢复', '需要专业体能训练方案'],
      safety: '运动请量力而行，出现疼痛或不适请停止并咨询专业人士。' },
    { id: 'clean', cat: 'bm', sub: 'phys', icon: '🌬️', name: '清爽生活搭子', href: '', soon: true,
      promise: '不靠硬扛，陪你一点点把依赖松开。', alias: '戒烟 戒酒 戒断 依赖',
      problems: ['戒过很多次，又悄悄回去了', '一有压力就想来一根 / 来一杯', '家人越劝，心里越烦'],
      short: ['反复复吸', '压力大就破', '戒断反应'],
      tags: ['#戒烟酒', '#身体健康', '#意志力', '#习惯矫正'],
      duration: '28天计划', dailyTime: '每天约5分钟', badge: '新上线',
      tasks: ['今天把第一根 / 第一杯延后30分钟', '想来一根时，先喝一大口水', '记一次：是什么让你特别想来一根'],
      suit: ['想戒但反复失败', '不想被说教', '希望有人每天陪着数'],
      unsuit: ['有严重物质依赖，请先寻求专业戒断机构'],
      safety: '本搭子提供日常陪伴与习惯支持，不替代医疗戒断治疗；如有严重依赖请寻求专业机构帮助。' },
    { id: 'health', cat: 'bm', sub: 'phys', icon: '🛡️', name: '健康底盘搭子', href: '搭子-健康底盘.html',
      promise: '陪你把血压、睡眠、运动这些底盘稳稳守住。', alias: '体检 指标 三高',
      problems: ['体检查出指标异常，心里没底', '想管理健康，不知从哪开始', '作息乱、动得少，越拖越焦虑'],
      short: ['指标异常', '没方向', '底子虚'],
      tags: ['#身体健康', '#体检', '#习惯矫正'],
      duration: '14天体验', dailyTime: '每天约5分钟', badge: '新手推荐',
      tasks: ['今晚比昨天早睡15分钟', '饭后散步15分钟', '记录今天的血压/状态'],
      suit: ['想系统性打理健康', '体检有轻度异常', '想建立健康日常'],
      unsuit: ['需要疾病诊断治疗', '有持续严重症状'],
      safety: '本搭子用于习惯建立和日常生活支持，不提供疾病诊断或医疗治疗；如存在持续或严重身体问题，应优先寻求专业医疗帮助。' },
    { id: 'bodyfriend', cat: 'bm', sub: 'phys', icon: '🤝', name: '和身体做朋友搭子', href: '搭子-身体朋友.html',
      promise: '陪你重新听懂身体的信号，不再硬扛。', alias: '疲劳 过劳 身体信号',
      problems: ['总是很累，却说不清哪里累', '经常忽视身体的报警信号', '对自己太狠，不会照顾自己'],
      short: ['硬扛', '过劳', '忽视信号'],
      tags: ['#身体健康', '#疲劳', '#情绪'],
      duration: '14天体验', dailyTime: '每天约4分钟', badge: '',
      tasks: ['扫描一下身体，哪里的紧绷最明显？', '给它 5 分钟放松', '睡前说一句感谢身体的话'],
      suit: ['长期疲劳的打工人', '习惯硬扛不爱喊累', '想改善身体觉察'],
      unsuit: ['需要医学评估的疼痛', '严重睡眠障碍'] },
    { id: 'muscle', cat: 'bm', sub: 'phys', icon: '💪', name: '肌肉搭子', href: '搭子-肌肉.html',
      promise: '陪你科学增肌，练得出、留得住。', alias: '增肌 力量 体态',
      problems: ['练了很久，看不到变化', '三分钟热度，坚持不下来', '瞎练怕受伤，不知道怎么练'],
      short: ['没效果', '难坚持', '怕受伤'],
      tags: ['#运动', '#身体健康', '#体态'],
      duration: '21天计划', dailyTime: '每天约10分钟', badge: '',
      tasks: ['今天完成一组基础力量动作', '记录蛋白质摄入', '睡前拉伸5分钟'],
      suit: ['健身新手', '练过但没体系', '想改善体态线条'],
      unsuit: ['有运动损伤未恢复', '需专业体能训练'] },
    { id: 'bodywealth', cat: 'bm', sub: 'phys', icon: '💚', name: '身体本钱搭子', href: '搭子-身体财富.html',
      promise: '把身体当第一本钱来经营，运动睡眠一手抓。', alias: '身体财富 精力 透支',
      problems: ['健康总排在日程最后', '运动睡眠反复失衡', '年轻拿命换钱，心里发虚'],
      short: ['失衡', '没精力', '透支'],
      tags: ['#身体健康', '#精力', '#长期主义'],
      duration: '21天计划', dailyTime: '每天约6分钟', badge: '',
      tasks: ['记录今天的运动/睡眠', '完成一次10分钟快走', '给下周定一个身体小目标'],
      suit: ['工作忙但想守住健康', '想要系统健康框架', '开始关注长期身体资本'],
      unsuit: ['需要医疗干预', '急性疾病期'] },
    /* ═══════════ 身心 · 心理疗愈 ═══════════ */
    { id: 'state', cat: 'bm', sub: 'mind', icon: '🌈', name: '情绪搭子', href: '搭子-状态.html',
      promise: '情绪低、精力差的时候，有个人先陪你缓一缓。', alias: '状态 心情 低落 焦虑',
      problems: ['最近总是提不起劲', '情绪起伏大，容易烦躁', '状态时好时坏，像开盲盒'],
      short: ['情绪低', '易烦躁', '不稳定'],
      tags: ['#情绪', '#焦虑', '#低谷期', '#自我接纳'],
      duration: '7天轻陪伴', dailyTime: '每天约3分钟', badge: '新手推荐',
      tasks: ['用一句话记下此刻的情绪', '做一次1分钟深呼吸', '今天给自己安排一件小确幸'],
      suit: ['最近压力大情绪波动', '想要轻量情绪陪伴', '不想被说教'],
      unsuit: ['持续情绪低落超两周', '需要心理诊断治疗'],
      safety: '本搭子提供日常情绪陪伴，不替代心理咨询与治疗；如情绪持续困扰，请寻求专业帮助。' },
    { id: 'mindset', cat: 'bm', sub: 'mind', icon: '🌸', name: '内耗搭子', href: '搭子-心态信念.html',
      promise: '陪你松动那些消耗自己的旧念头。', alias: '心态信念 想太多 自我苛责',
      problems: ['总是往坏处想，越想越怕', '对自己特别苛刻', '容易被一句话击垮'],
      short: ['灾难化', '自我苛责', '内耗'],
      tags: ['#内耗', '#情绪', '#自我接纳', '#认知'],
      duration: '21天陪伴', dailyTime: '每天约5分钟', badge: '热门',
      tasks: ['写下今天一个自动冒出的念头', '问自己：证据是什么？', '换一句更公平的话对自己说'],
      suit: ['容易内耗想很多', '想建立更稳的自我对话', '对心理学感兴趣'],
      unsuit: ['确诊心理疾病者', '持续抑郁焦虑请就医'],
      safety: '本搭子用于日常心态练习，不替代心理治疗；如有持续情绪困扰，请寻求专业帮助。' },
    /* ═══════════ 身心 · 日常状态 ═══════════ */
    { id: 'morning', cat: 'bm', sub: 'daily', icon: '☀️', name: '晨间启动搭子', href: '搭子-晨间启动.html',
      promise: '陪你把早晨变成一天里最稳的锚。', alias: '早起 赖床 早晨',
      problems: ['每天睁眼就刷手机，越刷越丧', '早上兵荒马乱，一天都赶', '想起早，总败给闹钟'],
      short: ['赖床', '刷手机', '没秩序'],
      tags: ['#作息', '#习惯矫正', '#专注'],
      duration: '14天体验', dailyTime: '每天约5分钟', badge: '',
      tasks: ['醒来先不碰手机，拉开窗帘', '写下今天最重要的1件事', '做2分钟唤醒伸展'],
      suit: ['想戒掉早起刷手机', '想要有序的早晨', '培养晨间节奏'],
      unsuit: ['夜班作息人群', '严重睡眠不足请先调整睡眠'] },
    { id: 'image', cat: 'bm', sub: 'daily', icon: '✨', name: '形象搭子', href: '搭子-形象.html',
      promise: '从护肤到仪态，陪你把外在状态打理出来。', alias: '穿搭 护肤 气质',
      problems: ['觉得自己状态显旧显垮', '穿搭发型一直没有章法', '想改变，不知从哪下手'],
      short: ['显垮', '没章法', '想改变'],
      tags: ['#形象', '#自信', '#日常'],
      duration: '14天体验', dailyTime: '每天约5分钟', badge: '',
      tasks: ['完成今天的基础护肤', '整理一套明天穿的衣服', '对镜子练1分钟好姿态'],
      suit: ['想提升外在状态', '形象想做减法提气质', '准备面试/重要场合'],
      unsuit: ['需要医美方案', '皮肤疾病请就医'] },
    { id: 'rest', cat: 'bm', sub: 'daily', icon: '🛋️', name: '休息一下', href: '休息一下.html',
      promise: '累了就歇一歇，这里有免费恢复区。', alias: '累了 暂停 放松',
      problems: ['现在很累，什么都不想做', '脑子转不动了', '只想安静待一会儿'],
      short: ['累了', '想暂停', '恢复'],
      tags: ['#疲惫', '#情绪', '#免费'],
      duration: '随时可来', dailyTime: '3分钟也行', badge: '免费',
      tasks: ['跟着做一次放松呼吸', '听自己说一句：辛苦了', '什么都不做，就坐一会儿'],
      suit: ['此刻就需要休息', '不想被安排任务', '只想被接住'],
      unsuit: [] },
    /* ═══════════ 搞钱 · 职场晋升 ═══════════ */
    { id: 'p78', cat: 'money', sub: 'career', icon: '📈', name: 'P7→P8 搭子', href: '搭子-P7-P8.html',
      promise: '陪你把工作从「做得多」升级到「影响更大」。', alias: '晋升 职级 大厂',
      problems: ['活干得最多，晋升没份', '干活很强，向上影响力弱', '到了瓶颈，不知差在哪'],
      short: ['晋升难', '影响力弱', '瓶颈期'],
      tags: ['#晋升', '#职场', '#影响力'],
      duration: '28天计划', dailyTime: '每天约8分钟', badge: '热门',
      tasks: ['今天做一件「被看见」的事', '用老板视角复盘一个决策', '推进一次跨团队协同'],
      suit: ['大厂高阶晋升冲刺', '技术强但影响力弱', '想完成职级跃迁'],
      unsuit: [] },
    { id: 'owner', cat: 'money', sub: 'career', icon: '🌿', name: '业务 Owner 搭子', href: '搭子-业务Owner.html',
      promise: '从执行者到 Owner，陪你把业务真正扛起来。', alias: '负责人 扛业务 全局',
      problems: ['活是自己的，功劳说不清', '天天救火，没有全局', '带不动人，事事自己上'],
      short: ['没全局', '救火', '带不动'],
      tags: ['#职场', '#管理', '#Owner'],
      duration: '21天计划', dailyTime: '每天约8分钟', badge: '',
      tasks: ['用数据讲清今天一个业务判断', '把一件事真正授权出去', '约一次客户/用户对话'],
      suit: ['新晋业务负责人', '想建立 Owner 视角', '想学会数据驱动'],
      unsuit: [] },
    { id: 'leader', cat: 'money', sub: 'career', icon: '🧭', name: '领导力管理搭子', href: '搭子-领导力管理.html',
      promise: '从管事到成就他人，陪你完成管理者进化。', alias: '带团队 管理 新晋管理',
      problems: ['自己冲锋，团队跟不上', '不好意思谈标准，关系很累', '每天被会议和杂事填满'],
      short: ['带人累', '没标准', '没聚焦'],
      tags: ['#管理', '#职场', '#沟通'],
      duration: '28天计划', dailyTime: '每天约8分钟', badge: '',
      tasks: ['给下属一次具体的反馈', '明确一件事的验收标准', '砍掉今天一个低价值会议'],
      suit: ['新晋管理者', '想学成就型领导', '想做聚焦与复盘'],
      unsuit: [] },
    /* ═══════════ 搞钱 · 创业搞钱 ═══════════ */
    { id: 'startup', cat: 'money', sub: 'biz', icon: '🚀', name: '创业搭子', href: '创业搭子.html',
      promise: '方向、产品、增长、心力，创业路上有人同行。', alias: '创业 项目 商业模式',
      problems: ['想法很多，不知哪个能成', '产品做出来，没人用', '一个人创业，太孤独'],
      short: ['选方向', '没用户', '孤独感'],
      tags: ['#创业', '#副业', '#孤独感'],
      duration: '28天陪伴', dailyTime: '每天约10分钟', badge: '',
      tasks: ['今天访谈一个真实用户', '把 MVP 再砍掉一个功能', '记录一个关键假设并验证'],
      suit: ['正在或准备创业', '想验证商业模式', '需要同行者与复盘'],
      unsuit: [] },
    { id: 'aiopc', cat: 'money', sub: 'biz', icon: '🎛️', name: 'AI 一人公司搭子', href: '搭子-AI-OPC创业.html',
      promise: '用 AI 员工跑通一人公司，轻装创业。', alias: 'AI OPC 超级个体 一人公司',
      problems: ['想创业，但没有团队', '人力成本高，跑不起模型', 'AI 工具很多，串不起来'],
      short: ['没团队', '成本高', '工具散'],
      tags: ['#创业', '#AI', '#副业'],
      duration: '21天计划', dailyTime: '每天约10分钟', badge: '新上线',
      tasks: ['把一个流程交给 AI 跑一遍', '砍掉一个不产生现金流的动作', '记录今天的获客实验'],
      suit: ['一人公司/超级个体', '想用 AI 降本增效', '轻资产创业'],
      unsuit: [] },
    { id: 'silver', cat: 'money', sub: 'biz', icon: '🌅', name: '银发经济创业搭子', href: '搭子-银发经济.html',
      promise: '陪你洞察银发赛道，做出有温度的生意。', alias: '银发 养老 老龄化',
      problems: ['看好银发赛道，不知从哪切入', '产品做了，老人不买账', '信任门槛高，获客难'],
      short: ['选赛道', '不接地气', '缺信任'],
      tags: ['#创业', '#银发', '#副业'],
      duration: '21天计划', dailyTime: '每天约8分钟', badge: '新上线',
      tasks: ['访谈一位长辈的真实需求', '把产品文案改说「人话」', '研究一个同行案例'],
      suit: ['关注老龄化机会', '做健康/服务/消费创业', '想建立信任型生意'],
      unsuit: [] },
    /* ═══════════ 搞钱 · 财务底盘 ═══════════ */
    { id: 'finance', cat: 'money', sub: 'wealth', icon: '💰', name: '财务底盘搭子', href: '搭子-财务财富.html',
      promise: '收入、储蓄、投资，陪你把财务底盘打牢。', alias: '财务财富 存钱 理财 记账',
      problems: ['赚得不少，存不下', '投资凭感觉，总当韭菜', '对财务状况心里没数'],
      short: ['存不下', '乱投资', '没账本'],
      tags: ['#存钱', '#理财', '#副业'],
      duration: '28天计划', dailyTime: '每天约5分钟', badge: '',
      tasks: ['记录今天的每一笔支出', '先存后花，转一笔小储蓄', '复盘一个投资决策'],
      suit: ['想建立财务秩序', '月光想改变', '投资想更理性'],
      unsuit: ['需要个股投资建议', '严重债务问题请咨询专业机构'] },
    /* ═══════════ 关系 · 情感疗愈 ═══════════ */
    { id: 'breakup', cat: 'rel', sub: 'heal', icon: '🫂', name: '低谷陪伴搭子', href: '', soon: true,
      promise: '不劝你想开点，陪你把这段最难的路走过去。', alias: '分手 戒断 失恋 离婚 重建',
      problems: ['分开很久了，还是会突然难过', '明知道不值得，还是忍不住联系', '白天还好，晚上最难熬'],
      short: ['走不出来', '忍不住联系', '夜里难熬'],
      tags: ['#情绪', '#关系', '#低谷期', '#分手', '#习惯矫正'],
      duration: '28天陪伴', dailyTime: '每天约5分钟', badge: '新上线',
      tasks: ['今天把想发的那条消息，先存草稿', '晚上给自己安排一件具体的小事', '记一句：今天比昨天好一点的地方'],
      suit: ['刚结束一段重要关系', '反复、走不出来的人', '不想被劝「想开点」'],
      unsuit: ['有自伤念头，请立刻联系专业心理援助或身边可信赖的人'],
      safety: '本搭子提供日常陪伴，不替代心理咨询；如出现持续失眠、强烈绝望或自伤念头，请立即寻求专业心理援助。' },
    /* ═══════════ 关系 · 家人亲子 ═══════════ */
    { id: 'peidu', cat: 'rel', sub: 'family', icon: '👩‍👧', name: '陪读妈妈搭子', href: '陪读妈妈搭子.html',
      promise: '情绪、沟通、平衡，陪你稳住陪读这场持久战。', alias: '陪读 育儿 作业',
      problems: ['一辅导作业就上头', '为孩子付出全部，却丢了自己', '和孩子的沟通越来越难'],
      short: ['易上头', '失去自我', '沟通难'],
      tags: ['#亲子', '#情绪', '#边界'],
      duration: '21天陪伴', dailyTime: '每天约5分钟', badge: '热门',
      tasks: ['发火前先做一次深呼吸', '今天夸孩子一个具体行为', '给自己留10分钟独处'],
      suit: ['陪读中的妈妈', '想改善亲子沟通', '想找回自己节奏'],
      unsuit: [] },
    { id: 'family', cat: 'rel', sub: 'family', icon: '🏡', name: '家人相处搭子', href: '搭子-家人相处.html',
      promise: '好好说话、相互托举，把家变成充电的地方。', alias: '父母 家人 原生家庭',
      problems: ['对外客气，对家人易发火', '家人之间不会表达爱', '一回家就吵架，很无力'],
      short: ['易发火', '难表达', '常吵架'],
      tags: ['#家人', '#沟通', '#边界'],
      duration: '21天陪伴', dailyTime: '每天约5分钟', badge: '',
      tasks: ['对家人说一句具体的欣赏', '把一句反问换成陈述', '创造一个小仪式时刻'],
      suit: ['想改善家庭氛围', '不会对家人表达', '想减少家庭冲突'],
      unsuit: [] },
    { id: 'fujiaoyu', cat: 'rel', sub: 'family', icon: '🏦', name: '富教育搭子', href: '搭子-富教育.html',
      promise: '财商、试错、主见，给孩子真正富足的教育。', alias: '教育 财商 孩子',
      problems: ['孩子一要东西就头疼', '不知怎么培养孩子主见', '怕养出巨婴，又不敢放手'],
      short: ['财商盲', '没主见', '不敢放手'],
      tags: ['#亲子', '#教育', '#财商'],
      duration: '21天陪伴', dailyTime: '每天约5分钟', badge: '',
      tasks: ['让孩子体验一次选择的后果', '用提问代替给答案', '聊一个金钱话题'],
      suit: ['注重孩子财商与独立', '想少说教多引导', '学习型父母'],
      unsuit: [] },
    { id: 'happiness', cat: 'rel', sub: 'family', icon: '🌷', name: '幸福力搭子', href: '搭子-幸福力.html',
      promise: '自信、勇敢、乐观，陪你和孩子一起长出幸福力。', alias: '幸福 自信 乐观',
      problems: ['孩子不自信，遇事就退缩', '感知幸福的能力越来越弱', '想要乐观，但总看到坏的一面'],
      short: ['不自信', '易退缩', '感知弱'],
      tags: ['#亲子', '#自信', '#自我接纳'],
      duration: '21天陪伴', dailyTime: '每天约5分钟', badge: '',
      tasks: ['记录今天三个小确幸', '做一件小小的勇敢事', '给家人一次具体的肯定'],
      suit: ['想养出内心有光的孩子', '自己也想更幸福', '重视心理养育'],
      unsuit: [] },
    /* ═══════════ 关系 · 沟通连接 ═══════════ */
    { id: 'guanxi', cat: 'rel', sub: 'social', icon: '🌸', name: '关系力修炼搭子', href: '搭子-关系力修复.html',
      promise: '倾听、表达、边界，陪你把关系修得更舒服。', alias: '关系力 沟通 冲突',
      problems: ['一说话就呛，事后又后悔', '不会拒绝，总被消耗', '在乎的关系，越处越累'],
      short: ['易冲突', '不会拒绝', '关系累'],
      tags: ['#沟通', '#边界', '#关系', '#冲突'],
      duration: '21天陪伴', dailyTime: '每天约6分钟', badge: '',
      tasks: ['今天先停3秒再回应', '练习说一次温和的拒绝', '记录一个共情瞬间'],
      suit: ['想改善沟通模式', '常被关系消耗', '想学边界与共情'],
      unsuit: ['正在受关系伤害，请先寻求支持'] },
    { id: 'relwealth', cat: 'rel', sub: 'social', icon: '❤️', name: '关系账户搭子', href: '搭子-关系财富.html',
      promise: '家人、朋友、连接，陪你经营人生最重要的账户。', alias: '关系财富 人脉 连接',
      problems: ['重要的人，很久没好好联系', '关系只在需要时才想起', '社交很多，连接很少'],
      short: ['失联', '浅社交', '缺连接'],
      tags: ['#关系', '#连接', '#孤独感'],
      duration: '21天陪伴', dailyTime: '每天约4分钟', badge: '',
      tasks: ['主动联系一位重要的人', '发出一次具体的感谢', '安排一次面对面见面'],
      suit: ['想深耕重要关系', '社交疲惫但渴望连接', '重视关系账户'],
      unsuit: [] },
    /* ═══════════ 自我 · 认知成长 ═══════════ */
    { id: 'cognition', cat: 'self', sub: 'think', icon: '🕸️', name: '认知思维搭子', href: '搭子-认知思维.html',
      promise: '陪你练深度思考，从知道走到做到。', alias: '思维 思考 决策',
      problems: ['学了很多，用不出来', '思考总停在表面', '道理都懂，还是老样子'],
      short: ['学用脱节', '浅思考', '知道做不到'],
      tags: ['#认知', '#学习', '#决策'],
      duration: '21天计划', dailyTime: '每天约8分钟', badge: '',
      tasks: ['用一个「为什么」追问今天的判断', '把一个观点画成网状图', '输出一段100字思考'],
      suit: ['爱学习但用不出来', '想升级思维方式', '做决策容易凭感觉'],
      unsuit: [] },
    { id: 'fuzhixing', cat: 'self', sub: 'think', icon: '🦋', name: '富知行搭子', href: '搭子-富知行.html',
      promise: '注意力、圈子、行动，陪你把知变成行。', alias: '知行合一 注意力 圈子',
      problems: ['时间总被琐事吃掉', '圈子固定，视野打不开', '想改变总是启动不了'],
      short: ['注意力散', '圈子窄', '启动难'],
      tags: ['#专注', '#认知', '#习惯矫正'],
      duration: '21天陪伴', dailyTime: '每天约6分钟', badge: '',
      tasks: ['记录今天注意力花在哪了', '主动连接一位想认识的人', '完成一个拖延已久的小行动'],
      suit: ['想拿回注意力主动权', '想突破现状', '相信知行合一'],
      unsuit: [] },
    { id: 'ai', cat: 'self', sub: 'think', icon: '🤖', name: 'AI 能力搭子', href: '搭子-AI能力.html',
      promise: '从工具到实战，陪你把 AI 变成真生产力。', alias: 'AI Prompt 提效',
      problems: ['AI 用得浅，只会聊天', 'Prompt 写不好，效果随缘', '学了不用，很快忘掉'],
      short: ['用得浅', 'Prompt弱', '难落地'],
      tags: ['#AI', '#学习', '#提效'],
      duration: '14天体验', dailyTime: '每天约10分钟', badge: '新上线',
      tasks: ['用 AI 完成今天一个真实任务', '迭代一条自己的 Prompt', '记录一个提效心得'],
      suit: ['想让 AI 提效的职场人', 'AI 新手到进阶', '喜欢动手实践'],
      unsuit: [] },
    { id: 'longterm', cat: 'self', sub: 'think', icon: '⏳', name: '长期主义搭子', href: '搭子-长期主义.html',
      promise: '陪你把时间从短视任务搬到长线价值。', alias: '复利 长期 积累',
      problems: ['天天很忙，年底却说不清做了什么', '重要不紧急的事一直被挤掉', '想投资自己，不知投哪'],
      short: ['瞎忙', '短视', '没积累'],
      tags: ['#长期主义', '#专注', '#决策'],
      duration: '28天计划', dailyTime: '每天约6分钟', badge: '',
      tasks: ['用 KEEP/STOP 给今天的事分类', '给长线目标投入30分钟', '记录一个复利时刻'],
      suit: ['想摆脱低效忙碌', '做长期重要的选择', '经营个人复利'],
      unsuit: [] },
    { id: 'spirit', cat: 'self', sub: 'think', icon: '🕊️', name: '内心富养搭子', href: '搭子-精神财富.html',
      promise: '阅读、冥想、成长，陪你富养自己的内心。', alias: '精神财富 阅读 冥想',
      problems: ['心总是静不下来', '书买了一堆，读不进去', '内在很空，靠刷手机填'],
      short: ['静不下', '读不进', '内心空'],
      tags: ['#阅读', '#自我接纳', '#情绪'],
      duration: '21天陪伴', dailyTime: '每天约8分钟', badge: '',
      tasks: ['冥想5分钟', '读10页书并记一句触动', '写下今天一个成长瞬间'],
      suit: ['想建立阅读/冥想习惯', '想充实内心世界', '偏爱安静的成长'],
      unsuit: [] },
    /* ═══════════ 自我 · 行动习惯 ═══════════ */
    { id: 'discipline', cat: 'self', sub: 'act', icon: '🪨', name: '坚持自律搭子', href: '搭子-坚持自律.html',
      promise: '不靠意志力硬扛，陪你把坚持变成系统。', alias: '自律 坚持 习惯',
      problems: ['什么都能坚持三天', '计划定得很满，执行很骨感', '一中断就全放弃'],
      short: ['三分钟热度', '计划落空', '易放弃'],
      tags: ['#习惯矫正', '#意志力', '#专注'],
      duration: '21天计划', dailyTime: '每天约5分钟', badge: '热门',
      tasks: ['只完成今天最小的一步', '中断了？记录原因，不评判', '连续打卡可视化一下'],
      suit: ['反复开始又放弃', '想建立长期习惯', '讨厌被硬性约束'],
      unsuit: [] },
    { id: 'subject', cat: 'self', sub: 'act', icon: '🦁', name: '主体性搭子', href: '搭子-主体性.html',
      promise: '陪你从「我知道」慢慢走到「我做到」。', alias: '表达 不敢说 讨好',
      problems: ['反应总是慢半拍，事后才想起怎么回', '经常犹豫、不敢表达', '想很多，做很少，很消耗'],
      short: ['犹豫', '内耗', '不敢表达'],
      tags: ['#表达', '#边界', '#自信', '#关系'],
      duration: '21天计划', dailyTime: '每天约8分钟', badge: '热门',
      tasks: ['今天主动表达一次真实想法', '记录一个「当时想说而没说」的场景', '做一次3分钟的当场练习'],
      suit: ['职场中不敢发声', '习惯性讨好退让', '想练表达和场感'],
      unsuit: [] },
    /* ═══════════ 自我 · 意义方向 ═══════════ */
    { id: 'restart40', cat: 'self', sub: 'meaning', icon: '⛰️', name: '40岁重启搭子', href: '搭子-40岁重启.html',
      promise: '觉醒、盘点、实验，人生下半场重新出发。', alias: '中年 转型 第二曲线',
      problems: ['到了中年，突然很迷茫', '想转型，不知还能做什么', '体能和心气都在下滑'],
      short: ['中年迷茫', '想转型', '心气低'],
      tags: ['#中年', '#转型', '#低谷期', '#长期主义'],
      duration: '28天计划', dailyTime: '每天约8分钟', badge: '',
      tasks: ['做一次人生盘点', '开启一个小成本实验', '完成一次体能行动'],
      suit: ['35+想重启人生', '寻求第二曲线', '想重拾体能与心气'],
      unsuit: [] },
    { id: 'mission', cat: 'self', sub: 'meaning', icon: '🎯', name: '人生使命搭子', href: '搭子-使命财富.html',
      promise: '目标、价值、贡献，陪你找到并活出自己的使命。', alias: '使命 意义 方向',
      problems: ['日子稳定，却不知道为什么而活', '想要意义感，无从找起', '总在为别人活'],
      short: ['无意义感', '迷茫', '为别人活'],
      tags: ['#意义', '#方向', '#自我接纳'],
      duration: '28天计划', dailyTime: '每天约8分钟', badge: '',
      tasks: ['写下今天最有价值感的瞬间', '问自己：我想留下什么？', '做一件利他小事'],
      suit: ['寻找人生方向', '想要意义感', '愿意向内探索'],
      unsuit: [] }
  ]
};
/* 热门精选（首页/搭子馆「大家最近都在找」） */
window.V3.featured = ['sleep', 'slim', 'mindset', 'p78'];
window.V3.partnerById = function (id) {
  for (var i = 0; i < window.V3.partners.length; i++) if (window.V3.partners[i].id === id) return window.V3.partners[i];
  return null;
};
window.V3.catOf = function (key) {
  for (var i = 0; i < window.V3.cats.length; i++) if (window.V3.cats[i].key === key) return window.V3.cats[i];
  return { key: key, label: '', emoji: '', tip: '' };
};
window.V3.subLabel = function (cat, sub) {
  var arr = window.V3.subs[cat] || [];
  for (var i = 0; i < arr.length; i++) if (arr[i].key === sub) return arr[i].label;
  return '';
};
window.V3.moodOf = function (key) {
  for (var i = 0; i < window.V3.moods.length; i++) if (window.V3.moods[i].key === key) return window.V3.moods[i];
  return null;
};
